name: manitto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  
  excel: ^4.0.6
  get: ^4.7.2
  flutter_email_sender: ^7.0.0
  mailer: ^6.0.0
  image: ^4.3.0
  flutter_dotenv: ^5.2.1
  file_picker: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - .env

  fonts:
     - family: Pretentard
       fonts:
         - asset: assets\fonts\Pretendard\Pretendard-Thin.ttf
           weight: 100
         - asset: assets\fonts\Pretendard\Pretendard-ExtraLight.ttf
           weight: 200
         - asset: assets\fonts\Pretendard\Pretendard-Light.ttf
           weight: 300
         - asset: assets\fonts\Pretendard\Pretendard-Regular.ttf
           weight: 400
         - asset: assets\fonts\Pretendard\Pretendard-Medium.ttf
           weight: 500
         - asset: assets\fonts\Pretendard\Pretendard-SemiBold.ttf
           weight: 600
         - asset: assets\fonts\Pretendard\Pretendard-Bold.ttf
           weight: 700
         - asset: assets\fonts\Pretendard\Pretendard-ExtraBold.ttf
           weight: 800
